### ISSUE TITLE
Fingerprint is not working

### ISSUE THREAD

**Issue by LuanHalaiko** [ryan-andri/android_kernel_santoni#1]
Since the latest commits fingerprint stoped working on v27 firmware

**Comment by ryan-andri** [comment]
@LuanHalaiko never expected this, i'll revert the latest FP commit, thanks buddy.

**Comment by LuanHalaiko** [comment]
Nonono it was a mistake, I din't follow your commits, so fingerprint driver wasn't enabled, this issue is not valid xD

**Comment by LuanHalaiko** [comment]
But the fingerprint delay still is here :/
