### ISSUE TITLE
About Darkness and Nightmare governors.

### ISSUE THREAD

**Issue by kda2495** [ryan-andri/android_kernel_santoni#10]
Hello! Just can I tell you about this governors? I think, they don't work properly, because they ramp up frequency to maximum when you make any operation on your smartphone. Maybe, they are useless? And can you add ROW I/O scheduler? Ok, and other questions: Maybe AutoSMP is useless? Why do you enable this, when our smartphone has core _control feature that can be tunable in /sys/devices/system/cpu/cpu0/core_ctl? And the last question: can you modify sound quality in your kernel, so we'll have sound like on MIUI in Nougat/Oreo ROM's? Some kernel developers tweak sound, maybe you can do this too? Thanks so much for your work!

**Comment by ryan-andri** [comment]
* row io scheduler is removed by CAF.
  row is not like can be take then add to the source, need some patch's for block too.
  its not easy like cherry-pick them. i'm still asking to my self, why caf removing row ?
  theres is some reason why, but i don't know.
* try ask Xiaomi to release their latest source code for sound quality.
  Did you know, Xiaomi give us shit source kernel for our device ?
  and i'm doubt they will give us update in future.
* you tell this "Maybe AutoSMP is useless? Why do you enable this"
  then don't enabling it, just leave hotplug by default with CAF core control.

**Comment by kda2495** [comment]
Ok, and about governors?

**Comment by ryan-andri** [comment]
you can tweak it self, that why sysfs or usespace created.
tweak it self, or use interactive as stable cpu governor.
i'll check it asap, i'll remove them on next release if necessary.
