### ISSUE TITLE
Mobile internet doesn't work when WiFi hotspot enabled.

### ISSUE THREAD

**Issue by kda2495** [ryan-andri/android_kernel_santoni#11]
On ViperOS mobile internet doesn't work when WiFi hotspot enabled. And it doesn't work even I reboot the phone. Can you check it and fix? I can send you dmesg and logcat. Please, fix this, this is my favourite ROM. I've heard that on version 1.8 hotspot works. And it's not ROM problem. Problem is in the kernel. I've installed MIUI version, but it still doesn't work.

**Comment by ryan-andri** [comment]
viperOS not with mi kernel and its build with custom kernel inbuilt.
yeah, i reworking on it, the problem from ipa tethering driver, will do changes it soon.

**Comment by kda2495** [comment]
And when hotspot via usb is on, mobile internet downstairs l doesn't work too.

**Comment by kda2495** [comment]
On version 4.1 the problem still exists.

**Comment by ryan-andri** [comment]
already pushed.
Please check thread @kda2495

**Comment by kda2495** [comment]
Thanks so much. I don't use ViperOS but it's useful for many users is other old ROMs) You are great!
