### ISSUE TITLE
Can't compile with HCI USB Driver (MIUI branch)

### ISSUE THREAD

**Issue by nkrapivin** [ryan-andri/android_kernel_santoni#5]
OS: Debian 9 amd64
Toolchain: Linaro GCC 4.9.4 x86_64-aarch64

**Comment by ryan-andri** [comment]
show the error message's please.

**Comment by nkrapivin** [comment]
LD      kernel/built-in.o
  CC      drivers/bluetooth/btusb.o
In file included from include/linux/module.h:17:0,
                 from drivers/bluetooth/btusb.c:23:
drivers/bluetooth/btusb.c: In function ‘__check_reset’:
include/linux/moduleparam.h:378:61: warning: return from incompatible pointer type
error, forbidden warning: moduleparam.h:378
scripts/Makefile.build:257: ошибка выполнения рецепта для цели «drivers/bluetooth/btusb.o»
make[2]: *** [drivers/bluetooth/btusb.o] Ошибка 1
scripts/Makefile.build:402: ошибка выполнения рецепта для цели «drivers/bluetooth»
make[1]: *** [drivers/bluetooth] Ошибка 2
Makefile:967: ошибка выполнения рецепта для цели «drivers»
make: *** [drivers] Error 2

**Comment by ryan-andri** [comment]
ok thanks, are you have do any change on bluethooth drivers ?
i'll check it

**Comment by nkrapivin** [comment]
I have just enabled HCI USB Driver.

**Comment by ryan-andri** [comment]
ok,  i'll mention if it solved, will check it asap, thanks.

**Comment by nkrapivin** [comment]
;) thx

**Comment by ryan-andri** [comment]
@nkrapivin hi, issue already fixed.
you need this commits:
4760c9ce07d6617d38cedbf973f580a040be9d2c and d334567e1c33c5ff6c8ace0ca36ebf10a2eb9015.
Thanks for your report.

**Comment by nkrapivin** [comment]
I know 'bout ATH3K but... well just one change. OK! Thanks.
