### ISSUE TITLE
CPU Hotplugging broken

### ISSUE THREAD

**Issue by Keridos** [ryan-andri/android_kernel_santoni#6]
Using v2.8 Oreo and your modded Kernel Adiutor:
It seems that CPU Hotplugging is severely broken in the kernel at this moment. QC own hotplugging ignores the number of cores settings completely, when turning on either AiO or AutoSMP most of the time all cores are online. AutoSMP settings do not work at all. I had some luck after rebooting and setting kernel parameters via kernel adiutor automatically and then reselecting a different hotplugging solution, but that rarely works. AutoSMP seems to limit the number of core used to 1 when screen is off, so that works. But no matter what I set (even lower maximum cores online) have any effect, it just keeps all cores online at all times.

**Comment by ryan-andri** [comment]
Yes confirmed.
i'm still working on that issue, it been my mistake.
for now you can use AIO hotplug or leave it by default hotplug.
Thanks.

**Comment by Keridos** [comment]
Is there something I could help you with?

**Comment by Keridos** [comment]
2.9 makes Kernel Adiutor not distinguish between little and big cores. Also, why should 1 big CPU be online all the time? 1 little core makes sense so you do not send all cores offline.

**Comment by mostafa-z** [comment]
probably to let kernel adiutor see big cluster, and let the app see governor's sysfs.
in my vision it can improve ui response !
https://github.com/ryan-andri/android_kernel_santoni/commit/d8556878fceaf2fed922a752b09c716ac11c3cac

**Comment by ryan-andri** [comment]
@Keridos **AutoSMP**: yes, sometime tubables on KA still doesn't show, but i was update KA to forcing AutoSMP showing up the tunables but not publish yet.
you probably missed what purpose custom hotplug maded. Big core is set as min 1 online because Big core really hungry about the power, while little set up by default 2 for small task. AutoSMP is smart hotplug, the cores will plug or unplug while they detect cpu at certain load.
**Clarity cpu governor**: if your prefering your device is under stress condition, i'll not suggest to use it. Poor performance ofcourse because my goal of that cpu governor for pressing power consumtion not for performace or under stressed ;)

@mostafa-z you right mate. but since the change of that commit, i feel device doesn't good stable, maybe i miss something.

**Comment by mostafa-z** [comment]
@ryan-andri as far as i could test, we should keep cpu0 enable to let it boot.
there is two or three more commits for it in workqueue and core(reverted in 1st link). recently he changed the structure.
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/8ac4a1820b300c7bc4c7be17879dc7e319253ee2
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/1a0fdf6483d5af2f3c201ab2147edf865d8cb251
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/0274c52d557c2e40c58625c0994a1accd407eaed
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/97f304b4813ce7f45f80a071a0f7f417c7c14d02

**Comment by Keridos** [comment]
I am fully aware of how and why we have big and little clusters. Even so, core 3 not being used at all is clearly a bug.

**Comment by Keridos** [comment]
Can you explain me why you set minimum big cores to 2 with that commit? Gonna start testing the latest sources on my devices shortly, got the cross compilation sorted out.

**Comment by ryan-andri** [comment]
how many big core you need with it ? you can increasing them using kernel adiutor, if you prefering all cores online you leave autosmp and enable aio.

**Comment by Keridos** [comment]
KA is currently broken, lots of settings do not show up anymore since 2.9

**Comment by ryan-andri** [comment]
owh if doesn't showup try this:
open ka
enable autosmp or aio then exit ka
kill ka from recent task and open it again
the tunables will showed up.

**Comment by Keridos** [comment]
Ah yeah that works. Another thing, can you limit the minimum setting for cores on big and little cluster to 1 instead of 0/disabled in KA ?

**Comment by Keridos** [comment]
Testing the commit from two days ago on my Smartphone since 2 days. Must say, good work, thank you, power saving is fairly impressive. Could you see if you can enable the lower frequency states of the cores? I think Gabriel kernel CPUs could be set to run at 200ish MHz and the GPU at 16MHz (yes 16!). Wondering if that could reduce power usage further.

**Comment by ryan-andri** [comment]
underclok need reordering voltage corner, it needed more work too.
currently i'm still trying this kernel migrate to old driver wlan caf,
the latest wlan driver seem doesn't good enough or doesn't fit for Nougat.
about the GPU i've try to underclock it, but device only get worse lag.
