### ISSUE TITLE
How can I compile the kernel on a linux machine?

### ISSUE THREAD

**Issue by Keridos** [ryan-andri/android_kernel_santoni#8]
Never crosscompiled a kernel before. How do you build the images? If you can share that information I might be able to help a bit here and there with the kernel.

**Comment by ryan-andri** [comment]
Check here for detail:
https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297

**Comment by Keridos** [comment]
TY
