### ISSUE TITLE
Clarity kernel

### ISSUE THREAD

**Issue by Rajdeep-4321** [ryan-andri/android_kernel_santoni#9]
I have 2gb varient and using clarity oc kernel.
Give me best modify setting to increase my device performance..

**Comment by ryan-andri** [comment]
Try give a comment or asking to this thread for some help/suggests from any people which using this kernel.
https://forum.xda-developers.com/xiaomi-redmi-4x/development/kernel-clarity-t3719341
This is not an issue.
